### ISSUE TITLE
Can't detect package after Flutter upgrade to 3.0.2

### ISSUE THREAD

**Issue by MohamedCharaabi** [sawankumarbundelkhandi/edge_detection#87]
After upgrading Flutter SDK from 3.0.1 to 3.0.2 I have encountered this error :
```
error: cannot find symbol
      flutterEngine.getPlugins().add(new com.sample.edgedetection.EdgeDetectionPlugin());
                                                                ^
  symbol:   class EdgeDetectionPlugin
  location: package com.sample.edgedetection
1 error
```

**Comment by sawankumarbundelkhandi** [comment]
I just ran the example sample from the repository and it just ran fine. 
I have even created a new sample to test and it's working fine as well. I have attached it here.


[flutter_application_1.zip](https://github.com/sawankumarbundelkhandi/edge_detection/files/8956160/flutter_application_1.zip)


![image](https://user-images.githubusercontent.com/10863510/174990594-b3a3ff86-77a4-4e0d-bf9d-5bafa00b607a.png)
